version: '3.8'

services:
  api:
    image: travanthien202/attendance-manager-api
    volumes:
      - ./API/:/var/www/html
    ports:
      - 8000:8000
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:8.0
    volumes:
      - ./API/.docker/data/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=attendance_management
      - MYSQL_ROOT_PASSWORD=kiaisoft
    restart: unless-stopped
  app:
    image: travanthien202/attendance-manager-fe
    volumes:
      - ./Frontend/index.html:/app/index.html
      - ./Frontend/package.json:/app/package.json
      - ./Frontend/src:/app/src
    ports:
      - 5173:5173
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
